version: "3.5"
services:
  postgres-global:
    image: postgres:latest
    container_name: postgres-global
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - "postgres-global:/var/lib/postgresql/data"
    restart: unless-stopped

volumes:
  postgres-global: